version: '3.9'
services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
